# Generated by Django 4.2.1 on 2023-05-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.URLField()),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
