# Generated by Django 4.2.1 on 2023-05-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
