# Generated by Django 4.2.1 on 2023-05-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='email_address',
            new_name='email',
        ),
    ]
